name: "finpulse"
version: "1.0.0"
config-version: 2

profile: "finpulse"

model-paths: ["models"]
seed-paths: ["seeds"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  finpulse:
    +materialized: view
